#script still needs info from python scrip server_name, admin_name, admin_password
---
- name: Provision Ubuntu Server
  hosts: "{{ server_name }}"
  become: yes
  vars:
    admin_name: "{{ admin_name }}"
    admin_password: "{{ admin_password }}"
  tasks:
    - name: "Update apt cache"
      apt:
        update_cache: yes
    - name: "Install python-minimal"
      apt:
        name: python-minimal
        state: present
        
    - name: "Install Ubuntu Server"
      apt:
        name: ubuntu-server
        state: present

    - name: "Install GNOME"
      apt:
        name: gnome-shell
        state: present

    - name: "Install XRDP"
      apt:
        name: xrdp
        state: present

    - name: "Enable XRDP"
      systemd:
        name: xrdp
        enabled: yes
        state: started

    - name: "Set admin password for XRDP"
      copy:
        content: "gnome-session --session=ubuntu-2d\n"
        dest: /etc/xrdp/startwm.sh
      notify: restart xrdp

  handlers:
    - name: "restart xrdp"
      systemd:
        name: xrdp
        state: restarted
